### ISSUE TITLE
docker issue (ModuleNotFoundError: No module named 'pycparser')

### ISSUE THREAD

**Issue by ferhaterata** [dynaroars/dig#46]
Hi Vu,

The first example, which runs dig on a trace files, completes successfully as follows:

`time ~/miniconda3/bin/python3 -O dig.py  ../tests/traces/cohendiv.csv -log 4`

```bash
root@fe8ccbdc800b:/dig/src# time ~/miniconda3/bin/python3 -O dig.py  ../tests/traces/cohendiv.csv -log 4
settings:INFO:2023-03-09 21:41:36.973133: dig.py ../tests/traces/cohendiv.csv -log 4
data.traces:DEBUG:vtrace1: 98
vtrace2: 83 traces
alg:INFO:analyzing '../tests/traces/cohendiv.csv'
alg:DEBUG:seed=1678398096.94 (test 33)
alg:INFO:got 181 traces over 2 locs
alg:DEBUG:vtrace1: 98
vtrace2: 83
helpers.miscs:DEBUG:autodeg 3
helpers.miscs:DEBUG:(pure) dynamic inference:running 8 jobs using 8 threads: [1, 1, 1, 1, 1, 1, 1, 1]
helpers.miscs:DEBUG:getting upperbounds:running 176 jobs using 8 threads: [22, 22, 22, 22, 22, 22, 22, 22]
helpers.miscs:DEBUG:getting upperbounds:running 1368 jobs using 8 threads: [171, 171, 171, 171, 171, 171, 171, 171]
helpers.miscs:DEBUG:getting upperbounds:running 32 jobs using 8 threads: [4, 4, 4, 4, 4, 4, 4, 4]
helpers.miscs:DEBUG:getting upperbounds:running 72 jobs using 8 threads: [9, 9, 9, 9, 9, 9, 9, 9]
helpers.miscs:DEBUG:solving 35 uks using 52 eqts
helpers.miscs:DEBUG:got 14 eqts after instantiating
helpers.miscs:DEBUG:ignoring large coefs 8*q**3 - 14*q**2*x - 80*q**2 + 7*q*x**2 + 140*q*x  ..
helpers.miscs:DEBUG:Grobner basis: from 13 to 3 ps
helpers.miscs:DEBUG:got 3 eqts after refinement
helpers.miscs:DEBUG:solving 84 uks using 98 eqts
helpers.miscs:DEBUG:got 19 eqts after instantiating
helpers.miscs:DEBUG:Grobner basis: from 19 to 3 ps
helpers.miscs:DEBUG:got 3 eqts after refinement
alg:DEBUG:check 546 invs using 181 traces
helpers.miscs:DEBUG:test_dinvs:running 2 jobs using 2 threads: [1, 1]
helpers.miscs:DEBUG:test:running 74 jobs using 8 threads: [9, 9, 9, 9, 9, 9, 10, 10]
helpers.miscs:DEBUG:test:running 472 jobs using 8 threads: [59, 59, 59, 59, 59, 59, 59, 59]
infer.inv:DEBUG:remove r**2 - r*x == 0
infer.inv:DEBUG:remove q*r == 0
helpers.miscs:DEBUG:test_dinvs: removed 2 invs in 1.39s (orig 546, new 544)
alg:INFO:check 546 invs using 181 traces (1.39s)
alg:DEBUG:simplify 544 invs
alg:DEBUG:vtrace1 (472 invs):
1. a*y - b == 0
2. q*y + r - x == 0
3. a*r - a*x + b*q == 0
4. -q <= 0
5. -b <= -1
6. -x <= -8
7. -r <= -1
8. -y <= -1
9. -a <= -1
10. a - b <= 0
11. a - r <= 0
12. b - x <= 0
13. r - x <= 0
14. b - r <= 0
15. -b + y <= 0
16. -r + y <= 0
17. q - x <= -1
18. a - x <= -5
19. -a - y <= -2
20. -x + y <= -6
21. ...
vtrace2 (72 invs):
1. q*y + r - x == 0
2. -r <= 0
3. -q <= 0
4. -x <= -1
5. -y <= -1
6. r - x <= 0
7. q - x <= 0
8. r - y <= -1
9. -q - r <= -1
10. -r - y <= -1
11. -q - y <= -5
12. -r - x <= -2
13. -q - x <= -1
14. -x - y <= -10
15. max(q, 0) - x <= 0
16. min(r, 0) - q <= 0
17. q - max(x, y) <= 0
18. min(r, y) - x <= 0
19. min(x, 0) - r <= 0
20. max(q, r) - x <= 0
21. ...
helpers.miscs:DEBUG:simplify:running 2 jobs using 2 threads: [1, 1]
helpers.miscs:DEBUG:_simplify_fast 58 mps_ieq:running 58 jobs using 8 threads: [7, 7, 7, 7, 7, 7, 8, 8]
helpers.miscs:DEBUG:_simplify_fast mps_ieq: removed 58 invs in 0.59s (orig 58, new 0)
helpers.miscs:DEBUG:_simplify_fast 9 octs:running 9 jobs using 8 threads: [1, 1, 1, 1, 1, 1, 1, 2]
helpers.miscs:DEBUG:_simplify_fast octs: removed 0 invs in 0.11s (orig 9, new 9)
helpers.miscs:DEBUG:_simplify_slow octs+mps: removed 6 invs in 0.29s (orig 9, new 3)
helpers.miscs:DEBUG:_simplify_slow octs_simple: removed 0 invs in 0.07s (orig 4, new 4)
helpers.miscs:DEBUG:_simplify_slow eqts: removed 1 invs in 1.81s (orig 3, new 2)
helpers.miscs:DEBUG:_simplify_fast 6 congruences:running 6 jobs using 6 threads: [1, 1, 1, 1, 1, 1]
helpers.miscs:DEBUG:_simplify_fast congruences: removed 0 invs in 0.06s (orig 6, new 6)
helpers.miscs:DEBUG:_simplify_slow congruences: removed 4 invs in 0.12s (orig 6, new 2)
helpers.miscs:DEBUG:_simplify_fast 432 mps_ieq:running 432 jobs using 8 threads: [54, 54, 54, 54, 54, 54, 54, 54]
helpers.miscs:DEBUG:_simplify_fast mps_ieq: removed 416 invs in 2.84s (orig 432, new 16)
helpers.miscs:DEBUG:_simplify_fast 23 octs:running 23 jobs using 8 threads: [2, 3, 3, 3, 3, 3, 3, 3]
helpers.miscs:DEBUG:_simplify_fast octs: removed 0 invs in 0.16s (orig 23, new 23)
helpers.miscs:DEBUG:_simplify_slow octs+mps: removed 30 invs in 0.86s (orig 39, new 9)
helpers.miscs:DEBUG:_simplify_slow octs_simple: removed 3 invs in 0.14s (orig 8, new 5)
infer.inv:DEBUG:done simplifying , time 5.989552021026611
helpers.miscs:DEBUG:simplify: removed 518 invs in 5.99s (orig 544, new 26)
alg:INFO:simplify 544 invs (5.99s)
vtrace1 (18 invs):
1. a*y - b == 0
2. q*y + r - x == 0
3. -q <= 0
4. -b <= -1
5. a - b <= 0
6. r - x <= 0
7. b - r <= 0
8. a - x <= -5
9. -b + y <= 0
10. -x + y <= -6
11. -a - q <= -1
12. -q - r <= -8
13. -x - y <= -10
14. -r - x <= -16
15. a + 2 - max(q, r, 0) <= 0
16. y + 2 - max(b, q, r, 0) <= 0
17. -q === 0 (mod 2)
18. -r - x === 0 (mod 2)
vtrace2 (8 invs):
1. q*y + r - x == 0
2. -r <= 0
3. -q <= 0
4. -x <= -1
5. r - x <= 0
6. q - x <= 0
7. r - y <= -1
8. -x - y <= -10

real	0m14.015s
user	1m4.844s
sys	0m1.995s
```

However, the other examples throw error: python cannot find `pycparser` although in the dockerfile I see that you'd added it.  

```bash
root@fe8ccbdc800b:/dig/src# time ~/miniconda3/bin/python3 -O dig.py  ../benchmark/c/nla/cohendiv.c -maxdeg 2 -noieqs -nominmax -log 4
settings:INFO:2023-03-09 21:47:55.507143: dig.py ../benchmark/c/nla/cohendiv.c -maxdeg 2 -noieqs -nominmax -log 4
alg:INFO:analyzing '../benchmark/c/nla/cohendiv.c'
alg:DEBUG:seed=1678398475.5 (test 7)
data.prog:ERROR:cmd 'python3 /dig/src/c_instrument.py ../benchmark/c/nla/cohendiv.c /var/tmp/dig_1152921506285245451_f9yt35aq/delete_me/symexe/cohendiv.c /var/tmp/dig_1152921506285245451_f9yt35aq/delete_me/traces/cohendiv.c' gives error
Traceback (most recent call last):
  File "/dig/src/c_instrument.py", line 3, in <module>
    from pycparser import c_generator, c_ast, c_parser 
ModuleNotFoundError: No module named 'pycparser'

Traceback (most recent call last):
  File "/dig/src/dig.py", line 272, in <module>
    dinvs = dig.start(seed=seed, maxdeg=args.maxdeg)
  File "/dig/src/alg.py", line 113, in start
    self.mysrc = self.mysrc_cls(self.filename, self.tmpdir_del)
  File "/dig/src/data/prog.py", line 361, in __init__
    super().__init__(filename, tmpdir)
  File "/dig/src/data/prog.py", line 275, in __init__
    cp = subprocess.run(
  File "/root/miniconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/dig/src/c_instrument.py', '../benchmark/c/nla/cohendiv.c', '/var/tmp/dig_1152921506285245451_f9yt35aq/delete_me/symexe/cohendiv.c', '/var/tmp/dig_1152921506285245451_f9yt35aq/delete_me/traces/cohendiv.c']' returned non-zero exit status 1.

real	0m0.658s
user	0m0.583s
sys	0m0.075s
root@fe8ccbdc800b:/dig/src#
```

**Comment by nguyenthanhvuh** [comment]
Could you try build the Docker again?  The newer version of the Dockerfile includes `pycparser`.

**Comment by ferhaterata** [comment]
yes, I did a fresh installation from the latest commit, here is the result:

```bash
docker build . -t='dig'
[+] Building 2.1s (18/18) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                  0.0s
 => => transferring dockerfile: 3.19kB                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/debian:bullseye                                                                                                                    0.2s
 => [ 1/14] FROM docker.io/library/debian:bullseye@sha256:f81bf5a8b57d6aa1824e4edb9aea6bd5ef6240bcc7d86f303f197a2eb77c430f                                                            0.0s
 => [internal] load build context                                                                                                                                                     0.4s
 => => transferring context: 29.05MB                                                                                                                                                  0.4s
 => CACHED [ 2/14] RUN apt-get update -y                                                                                                                                              0.0s
 => CACHED [ 3/14] RUN apt-get install -y build-essential git software-properties-common emacs  wget openjdk-11-jdk unzip                                                             0.0s
 => CACHED [ 4/14] RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh                                                                                     0.0s
 => CACHED [ 5/14] RUN bash ./Miniconda3-latest-Linux-x86_64.sh -b                                                                                                                    0.0s
 => CACHED [ 6/14] RUN /root/miniconda3/bin/conda install sympy pip -y                                                                                                                0.0s
 => CACHED [ 7/14] RUN /root/miniconda3/bin/pip3 install z3-solver beartype pycparser                                                                                                 0.0s
 => CACHED [ 8/14] RUN rm -rf ./Miniconda3-latest-Linux-x86_64.sh                                                                                                                     0.0s
 => [ 9/14] COPY . /dig                                                                                                                                                               0.1s
 => [10/14] WORKDIR /dig/EXTERNAL_FILES                                                                                                                                               0.0s
 => [11/14] RUN tar xf CIVL-1.21_5476.tgz ; ln -sf CIVL-1.21_5476/ civl                                                                                                               0.6s
 => [12/14] RUN cp dot_sarl ~/.sarl   # NEED TO MANUALLY PUT IN Z3 VERSION                                                                                                            0.4s
 => [13/14] WORKDIR /dig/src                                                                                                                                                          0.0s
 => exporting to image                                                                                                                                                                0.4s
 => => exporting layers                                                                                                                                                               0.4s
 => => writing image sha256:777c47a15f1246d97aea49d84bc2996abbd55a598fd4d85e7b2189bd290061fc                                                                                          0.0s
 => => naming to docker.io/library/dig                                                                                                                                                0.0s
ferhat@ferhat-XPS-13-9310:~/git/dig$ docker run -it dig
root@c4b18252a4de:/dig/src# time ~/miniconda3/bin/python3 -O dig.py  ../benchmark/c/nla/cohendiv.c -log 4
settings:INFO:2023-03-10 03:29:39.003173: dig.py ../benchmark/c/nla/cohendiv.c -log 4
alg:INFO:analyzing '../benchmark/c/nla/cohendiv.c'
alg:DEBUG:seed=1678418978.97 (test 53)
data.prog:ERROR:cmd 'python3 /dig/src/c_instrument.py ../benchmark/c/nla/cohendiv.c /var/tmp/dig_2236667786586399778_8b80esqr/delete_me/symexe/cohendiv.c /var/tmp/dig_2236667786586399778_8b80esqr/delete_me/traces/cohendiv.c' gives error
Traceback (most recent call last):
  File "/dig/src/c_instrument.py", line 3, in <module>
    from pycparser import c_generator, c_ast, c_parser
ModuleNotFoundError: No module named 'pycparser'

Traceback (most recent call last):
  File "/dig/src/dig.py", line 272, in <module>
    dinvs = dig.start(seed=seed, maxdeg=args.maxdeg)
  File "/dig/src/alg.py", line 113, in start
    self.mysrc = self.mysrc_cls(self.filename, self.tmpdir_del)
  File "/dig/src/data/prog.py", line 361, in __init__
    super().__init__(filename, tmpdir)
  File "/dig/src/data/prog.py", line 275, in __init__
    cp = subprocess.run(
  File "/root/miniconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/dig/src/c_instrument.py', '../benchmark/c/nla/cohendiv.c', '/var/tmp/dig_2236667786586399778_8b80esqr/delete_me/symexe/cohendiv.c', '/var/tmp/dig_2236667786586399778_8b80esqr/delete_me/traces/cohendiv.c']' returned non-zero exit status 1.

real	0m2.537s
user	0m2.366s
sys	0m0.169s
root@c4b18252a4de:/dig/src#
```

**Comment by nguyenthanhvuh** [comment]
I see the problem now. The program were using both `python3` and `miniconda3/bin/python3` and only the `miniconda3 python` has `pycparser` installed. 

The latest commit https://github.com/dynaroars/dig/commit/1be16cee79ab5505f4571df6774baed670dab57 should fix the issue.

**Comment by ferhaterata** [comment]
Thank you, Vu 👍 It works 🚀
